---
# defaults file for http
archive_src: /home/lb16096/developpment/livraisons/IPS_TOOLBOXES_2.6.1_1.1_LINUX7_6_GEN.tar
archive_dst: /home/lb16096/developpment/staging/IPS_TOOLBOXES_2.6.1_1.1_LINUX7_6_GEN.tar
tarfile: "{{ archive_dst|regex_replace('(.*)/([^/]+)$','\\2') }}"
dire: "{{ archive_dst|regex_replace('(.*)/([^/]+)$','\\1') }}"
tardir: "{{dire+'/'+tarfile|regex_replace('(.*)\\.([^\\.]+$)','\\1')}}"
install_dir: /home/lb16096/developpment/install
install_script: toolbox_install
install_script_source: toolbox_install
refpack_lin: /home/lb16096/developpment/RefPack_LIN
package_file: /home/lb16096/developpment/RefPack_LIN/IPS_TOOLBOXES_2.6.1_1.1_LINUX7_6_GEN.tar
sha_version: 2.6.1
delete_scripts_list:
 - Uninst_IPS_TOOLBOXES_MAN.ksh
 - Install_IPS_TOOLBOXES_MAN.ksh
